# Generated by Django 2.2.4 on 2021-03-25 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    atomic = False

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('lenth', models.IntegerField(blank=True, null=True)),
                ('radius', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Legs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('feet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Feets')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('leg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Legs')),
            ],
        ),
    ]
