# Generated by Django 2.2.4 on 2021-03-25 09:25

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feets',
            new_name='Feet',
        ),
        migrations.RenameModel(
            old_name='Legs',
            new_name='Leg',
        ),
    ]
