# Generated by Django 2.2.4 on 2021-03-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210325_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feet',
            old_name='lenth',
            new_name='length',
        ),
    ]
