# Generated by Django 2.2.4 on 2021-03-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210325_1642'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('name', 'leg')},
        ),
    ]
